### ISSUE TITLE
Error running with default settings.

### ISSUE THREAD

**Issue by cinjon** [batra-mlp-lab/lang-emerge#1]
When I run `run_me.sh` with useGPU turned off on python2.7, I get the following error:

```
Arguments:
           numRounds : 2
          hiddenSize : 100
         negFraction : 0.8
         imgFeatSize : 20
           batchSize : 1000
              useGPU : False
           qOutVocab : 3
             dataset : data/toy64_split_0.8.json
             rlScale : 100.0
        learningRate : 0.01
           embedSize : 20
           numEpochs : 1000000
           aOutVocab : 4
            remember : False
dataloader.py:69: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.3. Note that arange generates values in [start; end), not [start; end].
  self.rangeInds = torch.range(0, self.numInst['train']-1).long();
Answerer (
  (inNet): Embedding(7, 20)
  (outNet): Linear (100 -> 4)
  (softmax): Softmax ()
  (imgNet): Embedding(12, 20)
  (rnn): LSTMCell(80, 100)
)
Questioner (
  (inNet): Embedding(16, 20)
  (outNet): Linear (100 -> 3)
  (softmax): Softmax ()
  (rnn): LSTMCell(20, 100)
  (predictRNN): LSTMCell(20, 100)
  (predictNet): Linear (100 -> 12)
)
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    batchReward = team.backward(optimizer, batchLabels, epoch);
  File "lang-emerge/chatbots.py", line 273, in backward
    self.reward[firstMatch & secondMatch] = self.rlScale;
RuntimeError: inconsistent tensor size, expected tensor [1000 x 1] and mask [1000 x 1000] to have the same number of elements, but got 1000 and 1000000 elements respectively at /Users/soumith/code/builder/wheel/pytorch-src/torch/lib/TH/generic/THTensorMath.c:138
```

**Comment by satwikkottur** [comment]
Thanks for pointing this out!
